---
- job:
    name: distroinfo-base
    parent: tox
    abstract: true
    pre-run: playbooks/base.yaml

- job:
    name: distroinfo-base-py2
    parent: distroinfo-base
    abstract: true
    nodeset: centos-latest-pod

- job:
    name: distroinfo-base-py3
    parent: distroinfo-base
    abstract: true
    nodeset: fedora-latest-pod

- job:
    name: distroinfo-py2-centos
    parent: distroinfo-base-py2
    description: distroinfo tests on python2
    vars:
      tox_envlist: py2-unit

- job:
    name: distroinfo-py3-fedora
    parent: distroinfo-base-py3
    description: distroinfo tests on python3
    vars:
      tox_envlist: py3-unit

- job:
    name: distroinfo-py2-integration
    parent: distroinfo-base-py2
    description: distroinfo integration tests with rdoinfo
    vars:
      tox_envlist: py2-integration

- job:
    name: distroinfo-py3-integration
    parent: distroinfo-base-py3
    description: distroinfo integration tests with rdoinfo
    vars:
      tox_envlist: py3-integration

- job:
    name: distroinfo-codestyle
    parent: distroinfo-base-py2
    description: distroinfo code style checks
    vars:
      tox_envlist: pycodestyle

- job:
    name: distroinfo-dlrn-master
    parent: dlrn-base
    description: distroinfo integration tests with DLRN master
    run: playbooks/dlrn-master.yaml
    nodeset:
      nodes:
        - name: rdo-centos-8
          label: rdo-centos-8
    required-projects:
      - DLRN

- project:
    name: distroinfo
    check:
      jobs:
        - distroinfo-py2-centos
        - distroinfo-py3-fedora
        - distroinfo-py2-integration
        - distroinfo-py3-integration
        - distroinfo-codestyle
        - distroinfo-dlrn-master
    gate:
      jobs:
        - distroinfo-py2-centos
        - distroinfo-py3-fedora
        - distroinfo-py2-integration
        - distroinfo-py3-integration
        - distroinfo-codestyle
        - distroinfo-dlrn-master
    release:
      jobs:
        - upload-pypi
