---
- job:
    name: distroinfo-base
    parent: base
    pre-run: playbooks/base.yaml

- job:
    name: distroinfo-base-py2
    parent: distroinfo-base
    nodeset:
      nodes:
        - name: test-node
          label: centos-oci

- job:
    name: distroinfo-base-py3
    parent: distroinfo-base
    nodeset:
      nodes:
        - name: test-node
          label: fedora-oci

- job:
    name: distroinfo-py2-centos
    parent: distroinfo-base-py2
    description: distroinfo tests on python2
    run: playbooks/py2-tests.yaml

- job:
    name: distroinfo-py3-fedora
    parent: distroinfo-base-py3
    description: distroinfo tests on python3
    run: playbooks/py3-tests.yaml

- job:
    name: distroinfo-codestyle
    parent: distroinfo-base-py2
    description: distroinfo code style checks
    run: playbooks/codestyle.yaml

- project:
    name: distroinfo
    check:
      jobs:
        - distroinfo-py2-centos-7
        - distroinfo-py3-fedora-27
        - distroinfo-codestyle
    gate:
      jobs:
        - distroinfo-py2-centos-7
        - distroinfo-py3-fedora-27
        - distroinfo-codestyle
    release:
      jobs:
        - upload-pypi
