---
- hosts: all
  vars:
    working_dir: '{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/..'
  tasks:
    - name: Prepare virtualenv to test DLRN master
      shell:
        cmd: |
          tox -e py36 --notest
        chdir: "{{ working_dir }}/DLRN"
    - name: Inject distroinfo into DLRN master virtualenv
      shell:
        cmd: |
          . ../DLRN/.tox/py36/bin/activate
          python setup.py install
        chdir: "{{ working_dir }}/distroinfo"
    - name: Run DLRN master tests with distroinfo
      shell:
        cmd: |
          export TAG=""
          export TARGET="centos8"
          export ZUUL_BRANCH="rpm-master"
          export PYTHON_VERSION=py36
          timeout --signal=SIGKILL 3600 ./scripts/run_tests.sh http://review.rdoproject.org/r/rdoinfo.git ${TARGET} https://trunk.rdoproject.org/centos8/
        chdir: "{{ working_dir }}/DLRN"
    - name: Copy DLRN logs for collection
      shell:
        cmd: |
          cp -r DLRN/logs distroinfo/logs
        chdir: "{{ working_dir }}"
